export const siteConfig = {
  name: "MemoApp",
  url: "https://memoappbd.shop",
  description:
    "MemoApp is a Modern, AI-powered cloud-ready POS and shop management platform for Bangladeshi all types of retailers, combining billing, inventory, dues, purchases, reports, and AI assistance.",
  keywords: [
    "MemoApp",
    "SaaS POS",
    "ERP Software",
    "Bangladesh POS software",
    "Bangladesh ERP software",
    "shop management software",
    "inventory management",
    "customer dues tracking",
    "invoice software",
    "retail management",
    "AI-powered POS",
    "AI-powered shop management",
    "AI-powered inventory management",
    "AI-powered customer dues tracking",
    "AI-powered invoice software",
    "AI-powered retail management",
    "Bangla POS",
    "Bangla shop management",
    "Bangla inventory management",
    "Bangla customer dues tracking",
    "Bangla invoice software",
    "Bangla retail management",
    "Bangla language support",
    "Bangla invoice software",
    "Bangla retail management",
    "Bangla language support",
    "Bangla invoice software",
    "Bangla retail management",
    "Bangla language support",
    "Bangla invoice software",
    "Bangla retail management",
  ],
  contactEmail: "memoappbd@gmail.com",
};

export const brandColors = {
  primaryMain: "#02734A",
  primaryLight: "#e5f1ed",
  primaryDark: "#025940",
  secondaryMain: "#014034",
  secondaryLight: "#03A678",
  secondaryDark: "#024059",
  infoMain: "#FF9933",
  infoLight: "#FFB366",
  infoDark: "#FF8C33",
  backgroundDefault: "#f8f9f5",
  backgroundPaper: "#ffffff",
} as const;
